const PUZZLES = [
  { id: 1, clue: `MAN
BOARD`, answer: "Man Overboard" },
  { id: 2, clue: `STAND
—————
I`, answer: "I Understand" },
  { id: 3, clue: `THOUGHT`, answer: "Deep Thought" },
  { id: 4, clue: `R
E
A
D`, answer: "Read Up" },
  { id: 5, clue: `KNEE
LIGHTS`, answer: "Neon Lights" },
  { id: 6, clue: `ii ii`, answer: "See eye to eye" },
  { id: 7, clue: `TIMING TIMING`, answer: "Double Timing" },
  { id: 8, clue: `WAY
—————
S`, answer: "Subway" },
  { id: 9, clue: `LE
VEL`, answer: "Split Level" },
  { id: 10, clue: `DICE
DICE`, answer: "Paradise" },
  { id: 11, clue: `MCE MCE MCE`, answer: "Three Blind Mice" },
  { id: 12, clue: `LONG
WEAR`, answer: "Long Underwear" },
  { id: 13, clue: `HEAD
HEELS`, answer: "Head Over Heels" },
  { id: 14, clue: `CHART`, answer: "Off the Charts" },
  { id: 15, clue: `HISTORY HISTORY
HISTORY`, answer: "History repeats itself" },
  { id: 16, clue: `SYMPHON...`, answer: "Unfinished Symphony" },
  { id: 17, clue: `WOLF`, answer: "Wolf in sheep's clothing" },
  { id: 18, clue: `GIVE GIVE GIVE GIVE
GET GET GET GET`, answer: "Forgive and Forget" },
  { id: 19, clue: `ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE`, answer: "Tennis Shoes (Ten-issue)" },
  { id: 20, clue: `X Q Q Q ME`, answer: "Excuse Me" },
  { id: 21, clue: `HE'S/HIMSELF`, answer: "He's beside himself" },
  { id: 22, clue: `YOU ME`, answer: "Just between you and me" },
  { id: 23, clue: `TTTTTTTT`, answer: "Tea for two (T for 2)" },
  { id: 24, clue: `BUS`, answer: "Business" },
  { id: 25, clue: `PIPPED`, answer: "Pipped at the post" },
  { id: 26, clue: `EGG EGG`, answer: "Two eggs over easy" },
  { id: 27, clue: `PUNISHMENT`, answer: "Capital Punishment" },
  { id: 28, clue: `TOWN`, answer: "Man about town" },
  { id: 29, clue: `SEARCH
AND`, answer: "Search high and low" },
  { id: 30, clue: `FEET FEET FEET FEET
FEET FEET`, answer: "Six feet under" },
  { id: 31, clue: `NOON`, answer: "High Noon" },
  { id: 32, clue: `FALLING
LOVE`, answer: "Falling in love" },
  { id: 33, clue: `AGE`, answer: "Middle Age" },
  { id: 34, clue: `ROADS`, answer: "Crossroads" },
  { id: 35, clue: `MIND
MATTER`, answer: "Mind over matter" },
  { id: 36, clue: `KISS`, answer: "A big kiss" },
  { id: 37, clue: `TIME`, answer: "Time is up" },
  { id: 38, clue: `GROUND`, answer: "Six feet under ground" },
  { id: 39, clue: `CYCLE CYCLE CYCLE`, answer: "Tricycle" },
  { id: 40, clue: `DEAL`, answer: "Big Deal" },
  { id: 41, clue: `STOD`, answer: "Backwards" },
  { id: 42, clue: `POLICE`, answer: "Police on your tail" },
  { id: 43, clue: `LUCK`, answer: "Stroke of luck" },
  { id: 44, clue: `WEATHER`, answer: "Under the weather" },
  { id: 45, clue: `HEART`, answer: "Heart in the right place" },
  { id: 46, clue: `EYE`, answer: "Eye on the ball" },
  { id: 47, clue: `LIFE`, answer: "Life after death" },
  { id: 48, clue: `FRIENDS`, answer: "Friends in high places" },
  { id: 49, clue: `O_ER_T_O_`, answer: "Painless Operation" },
  { id: 50, clue: `TOUCH`, answer: "Touchdown" },
  { id: 51, clue: `VA DERS`, answer: "Space Invaders" },
  { id: 52, clue: `CHANCE`, answer: "Slim Chance" },
  { id: 53, clue: `BIRD`, answer: "Early Bird" },
  { id: 54, clue: `SECRET`, answer: "Top Secret" },
  { id: 55, clue: `PAINSTOP`, answer: "Stop and think" },
  { id: 56, clue: `JOB`, answer: "In between jobs" },
  { id: 57, clue: `GAGES`, answer: "Engages" },
  { id: 58, clue: `4GET`, answer: "Forget" },
  { id: 59, clue: `3D`, answer: "Third Dimension" },
  { id: 60, clue: `8 ATE 8`, answer: "Piece of cake" },
  { id: 61, clue: `B-SIDE`, answer: "Beside" },
  { id: 62, clue: `C-LEVEL`, answer: "Sea level" },
  { id: 63, clue: `G-STRING`, answer: "G-string" },
  { id: 64, clue: `T-BONE`, answer: "T-bone" },
  { id: 65, clue: `X-RAY`, answer: "X-ray" },
  { id: 66, clue: `P-POD`, answer: "Peas in a pod" },
  { id: 67, clue: `K-9`, answer: "Canine" },
  { id: 68, clue: `B-LINE`, answer: "Beeline" },
  { id: 69, clue: `Q-TIP`, answer: "Q-tip" },
  { id: 70, clue: `U-TURN`, answer: "U-turn" },
  { id: 71, clue: `I-OPENER`, answer: "Eye opener" },
  { id: 72, clue: `T-TIME`, answer: "Tea time" },
  { id: 73, clue: `E-MAIL`, answer: "Email" },
  { id: 74, clue: `B-BALL`, answer: "Basketball" },
  { id: 75, clue: `J-WALK`, answer: "Jaywalk" },
  { id: 76, clue: `C-SHORE`, answer: "Seashore" },
  { id: 77, clue: `U-BOAT`, answer: "U-boat" },
  { id: 78, clue: `V-NECK`, answer: "V-neck" },
  { id: 79, clue: `S-CAPE`, answer: "Escape" },
  { id: 80, clue: `B-STING`, answer: "Bee sting" },
  { id: 81, clue: `T-SHIRT`, answer: "T-shirt" },
  { id: 82, clue: `B-READY`, answer: "Be ready" },
  { id: 83, clue: `P-SOUP`, answer: "Pea soup" },
  { id: 84, clue: `I-LAND`, answer: "Island" },
  { id: 85, clue: `X-CHANGE`, answer: "Exchange" },
  { id: 86, clue: `T-LIGHT`, answer: "Tea light" },
  { id: 87, clue: `C-FOOD`, answer: "Seafood" },
  { id: 88, clue: `B-COOL`, answer: "Be cool" },
  { id: 89, clue: `G-FORCE`, answer: "G-force" },
  { id: 90, clue: `T-BAG`, answer: "Tea bag" },
  { id: 91, clue: `P-NUT`, answer: "Peanut" },
  { id: 92, clue: `B-HAVE`, answer: "Behave" },
  { id: 93, clue: `X-PRESS`, answer: "Express" },
  { id: 94, clue: `O-RING`, answer: "O-ring" },
  { id: 95, clue: `C-SAW`, answer: "Seasaw" },
  { id: 96, clue: `B-HIND`, answer: "Behind" },
  { id: 97, clue: `T-POT`, answer: "Teapot" },
  { id: 98, clue: `G-UNIT`, answer: "G-unit" },
  { id: 99, clue: `A-LIST`, answer: "A-list" },
  { id: 100, clue: `C-SIDE`, answer: "Seaside" },
  { id: 101, clue: `MAN
BOARD`, answer: "Man Overboard" },
  { id: 102, clue: `STAND
—————
I`, answer: "I Understand" },
  { id: 103, clue: `THOUGHT`, answer: "Deep Thought" },
  { id: 104, clue: `R
E
A
D`, answer: "Read Up" },
  { id: 105, clue: `KNEE
LIGHTS`, answer: "Neon Lights" },
  { id: 106, clue: `ii ii`, answer: "See eye to eye" },
  { id: 107, clue: `TIMING TIMING`, answer: "Double Timing" },
  { id: 108, clue: `WAY
—————
S`, answer: "Subway" },
  { id: 109, clue: `LE
VEL`, answer: "Split Level" },
  { id: 110, clue: `DICE
DICE`, answer: "Paradise" },
  { id: 111, clue: `MCE MCE MCE`, answer: "Three Blind Mice" },
  { id: 112, clue: `LONG
WEAR`, answer: "Long Underwear" },
  { id: 113, clue: `HEAD
HEELS`, answer: "Head Over Heels" },
  { id: 114, clue: `CHART`, answer: "Off the Charts" },
  { id: 115, clue: `HISTORY HISTORY
HISTORY`, answer: "History repeats itself" },
  { id: 116, clue: `SYMPHON...`, answer: "Unfinished Symphony" },
  { id: 117, clue: `WOLF`, answer: "Wolf in sheep's clothing" },
  { id: 118, clue: `GIVE GIVE GIVE GIVE
GET GET GET GET`, answer: "Forgive and Forget" },
  { id: 119, clue: `ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE`, answer: "Tennis Shoes (Ten-issue)" },
  { id: 120, clue: `X Q Q Q ME`, answer: "Excuse Me" },
  { id: 121, clue: `HE'S/HIMSELF`, answer: "He's beside himself" },
  { id: 122, clue: `YOU ME`, answer: "Just between you and me" },
  { id: 123, clue: `TTTTTTTT`, answer: "Tea for two (T for 2)" },
  { id: 124, clue: `BUS`, answer: "Business" },
  { id: 125, clue: `PIPPED`, answer: "Pipped at the post" },
  { id: 126, clue: `EGG EGG`, answer: "Two eggs over easy" },
  { id: 127, clue: `PUNISHMENT`, answer: "Capital Punishment" },
  { id: 128, clue: `TOWN`, answer: "Man about town" },
  { id: 129, clue: `SEARCH
AND`, answer: "Search high and low" },
  { id: 130, clue: `FEET FEET FEET FEET
FEET FEET`, answer: "Six feet under" },
  { id: 131, clue: `NOON`, answer: "High Noon" },
  { id: 132, clue: `FALLING
LOVE`, answer: "Falling in love" },
  { id: 133, clue: `AGE`, answer: "Middle Age" },
  { id: 134, clue: `ROADS`, answer: "Crossroads" },
  { id: 135, clue: `MIND
MATTER`, answer: "Mind over matter" },
  { id: 136, clue: `KISS`, answer: "A big kiss" },
  { id: 137, clue: `TIME`, answer: "Time is up" },
  { id: 138, clue: `GROUND`, answer: "Six feet under ground" },
  { id: 139, clue: `CYCLE CYCLE CYCLE`, answer: "Tricycle" },
  { id: 140, clue: `DEAL`, answer: "Big Deal" },
  { id: 141, clue: `STOD`, answer: "Backwards" },
  { id: 142, clue: `POLICE`, answer: "Police on your tail" },
  { id: 143, clue: `LUCK`, answer: "Stroke of luck" },
  { id: 144, clue: `WEATHER`, answer: "Under the weather" },
  { id: 145, clue: `HEART`, answer: "Heart in the right place" },
  { id: 146, clue: `EYE`, answer: "Eye on the ball" },
  { id: 147, clue: `LIFE`, answer: "Life after death" },
  { id: 148, clue: `FRIENDS`, answer: "Friends in high places" },
  { id: 149, clue: `O_ER_T_O_`, answer: "Painless Operation" },
  { id: 150, clue: `TOUCH`, answer: "Touchdown" },
  { id: 151, clue: `VA DERS`, answer: "Space Invaders" },
  { id: 152, clue: `CHANCE`, answer: "Slim Chance" },
  { id: 153, clue: `BIRD`, answer: "Early Bird" },
  { id: 154, clue: `SECRET`, answer: "Top Secret" },
  { id: 155, clue: `PAINSTOP`, answer: "Stop and think" },
  { id: 156, clue: `JOB`, answer: "In between jobs" },
  { id: 157, clue: `GAGES`, answer: "Engages" },
  { id: 158, clue: `4GET`, answer: "Forget" },
  { id: 159, clue: `3D`, answer: "Third Dimension" },
  { id: 160, clue: `8 ATE 8`, answer: "Piece of cake" },
  { id: 161, clue: `B-SIDE`, answer: "Beside" },
  { id: 162, clue: `C-LEVEL`, answer: "Sea level" },
  { id: 163, clue: `G-STRING`, answer: "G-string" },
  { id: 164, clue: `T-BONE`, answer: "T-bone" },
  { id: 165, clue: `X-RAY`, answer: "X-ray" },
  { id: 166, clue: `P-POD`, answer: "Peas in a pod" },
  { id: 167, clue: `K-9`, answer: "Canine" },
  { id: 168, clue: `B-LINE`, answer: "Beeline" },
  { id: 169, clue: `Q-TIP`, answer: "Q-tip" },
  { id: 170, clue: `U-TURN`, answer: "U-turn" },
  { id: 171, clue: `I-OPENER`, answer: "Eye opener" },
  { id: 172, clue: `T-TIME`, answer: "Tea time" },
  { id: 173, clue: `E-MAIL`, answer: "Email" },
  { id: 174, clue: `B-BALL`, answer: "Basketball" },
  { id: 175, clue: `J-WALK`, answer: "Jaywalk" },
  { id: 176, clue: `C-SHORE`, answer: "Seashore" },
  { id: 177, clue: `U-BOAT`, answer: "U-boat" },
  { id: 178, clue: `V-NECK`, answer: "V-neck" },
  { id: 179, clue: `S-CAPE`, answer: "Escape" },
  { id: 180, clue: `B-STING`, answer: "Bee sting" },
  { id: 181, clue: `T-SHIRT`, answer: "T-shirt" },
  { id: 182, clue: `B-READY`, answer: "Be ready" },
  { id: 183, clue: `P-SOUP`, answer: "Pea soup" },
  { id: 184, clue: `I-LAND`, answer: "Island" },
  { id: 185, clue: `X-CHANGE`, answer: "Exchange" },
  { id: 186, clue: `T-LIGHT`, answer: "Tea light" },
  { id: 187, clue: `C-FOOD`, answer: "Seafood" },
  { id: 188, clue: `B-COOL`, answer: "Be cool" },
  { id: 189, clue: `G-FORCE`, answer: "G-force" },
  { id: 190, clue: `T-BAG`, answer: "Tea bag" },
  { id: 191, clue: `P-NUT`, answer: "Peanut" },
  { id: 192, clue: `B-HAVE`, answer: "Behave" },
  { id: 193, clue: `X-PRESS`, answer: "Express" },
  { id: 194, clue: `O-RING`, answer: "O-ring" },
  { id: 195, clue: `C-SAW`, answer: "Seasaw" },
  { id: 196, clue: `B-HIND`, answer: "Behind" },
  { id: 197, clue: `T-POT`, answer: "Teapot" },
  { id: 198, clue: `G-UNIT`, answer: "G-unit" },
  { id: 199, clue: `A-LIST`, answer: "A-list" },
  { id: 200, clue: `C-SIDE`, answer: "Seaside" },
  { id: 201, clue: `MAN
BOARD`, answer: "Man Overboard" },
  { id: 202, clue: `STAND
—————
I`, answer: "I Understand" },
  { id: 203, clue: `THOUGHT`, answer: "Deep Thought" },
  { id: 204, clue: `R
E
A
D`, answer: "Read Up" },
  { id: 205, clue: `KNEE
LIGHTS`, answer: "Neon Lights" },
  { id: 206, clue: `ii ii`, answer: "See eye to eye" },
  { id: 207, clue: `TIMING TIMING`, answer: "Double Timing" },
  { id: 208, clue: `WAY
—————
S`, answer: "Subway" },
  { id: 209, clue: `LE
VEL`, answer: "Split Level" },
  { id: 210, clue: `DICE
DICE`, answer: "Paradise" },
  { id: 211, clue: `MCE MCE MCE`, answer: "Three Blind Mice" },
  { id: 212, clue: `LONG
WEAR`, answer: "Long Underwear" },
  { id: 213, clue: `HEAD
HEELS`, answer: "Head Over Heels" },
  { id: 214, clue: `CHART`, answer: "Off the Charts" },
  { id: 215, clue: `HISTORY HISTORY
HISTORY`, answer: "History repeats itself" },
  { id: 216, clue: `SYMPHON...`, answer: "Unfinished Symphony" },
  { id: 217, clue: `WOLF`, answer: "Wolf in sheep's clothing" },
  { id: 218, clue: `GIVE GIVE GIVE GIVE
GET GET GET GET`, answer: "Forgive and Forget" },
  { id: 219, clue: `ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE`, answer: "Tennis Shoes (Ten-issue)" },
  { id: 220, clue: `X Q Q Q ME`, answer: "Excuse Me" },
  { id: 221, clue: `HE'S/HIMSELF`, answer: "He's beside himself" },
  { id: 222, clue: `YOU ME`, answer: "Just between you and me" },
  { id: 223, clue: `TTTTTTTT`, answer: "Tea for two (T for 2)" },
  { id: 224, clue: `BUS`, answer: "Business" },
  { id: 225, clue: `PIPPED`, answer: "Pipped at the post" },
  { id: 226, clue: `EGG EGG`, answer: "Two eggs over easy" },
  { id: 227, clue: `PUNISHMENT`, answer: "Capital Punishment" },
  { id: 228, clue: `TOWN`, answer: "Man about town" },
  { id: 229, clue: `SEARCH
AND`, answer: "Search high and low" },
  { id: 230, clue: `FEET FEET FEET FEET
FEET FEET`, answer: "Six feet under" },
  { id: 231, clue: `NOON`, answer: "High Noon" },
  { id: 232, clue: `FALLING
LOVE`, answer: "Falling in love" },
  { id: 233, clue: `AGE`, answer: "Middle Age" },
  { id: 234, clue: `ROADS`, answer: "Crossroads" },
  { id: 235, clue: `MIND
MATTER`, answer: "Mind over matter" },
  { id: 236, clue: `KISS`, answer: "A big kiss" },
  { id: 237, clue: `TIME`, answer: "Time is up" },
  { id: 238, clue: `GROUND`, answer: "Six feet under ground" },
  { id: 239, clue: `CYCLE CYCLE CYCLE`, answer: "Tricycle" },
  { id: 240, clue: `DEAL`, answer: "Big Deal" },
  { id: 241, clue: `STOD`, answer: "Backwards" },
  { id: 242, clue: `POLICE`, answer: "Police on your tail" },
  { id: 243, clue: `LUCK`, answer: "Stroke of luck" },
  { id: 244, clue: `WEATHER`, answer: "Under the weather" },
  { id: 245, clue: `HEART`, answer: "Heart in the right place" },
  { id: 246, clue: `EYE`, answer: "Eye on the ball" },
  { id: 247, clue: `LIFE`, answer: "Life after death" },
  { id: 248, clue: `FRIENDS`, answer: "Friends in high places" },
  { id: 249, clue: `O_ER_T_O_`, answer: "Painless Operation" },
  { id: 250, clue: `TOUCH`, answer: "Touchdown" },
  { id: 251, clue: `VA DERS`, answer: "Space Invaders" },
  { id: 252, clue: `CHANCE`, answer: "Slim Chance" },
  { id: 253, clue: `BIRD`, answer: "Early Bird" },
  { id: 254, clue: `SECRET`, answer: "Top Secret" },
  { id: 255, clue: `PAINSTOP`, answer: "Stop and think" },
  { id: 256, clue: `JOB`, answer: "In between jobs" },
  { id: 257, clue: `GAGES`, answer: "Engages" },
  { id: 258, clue: `4GET`, answer: "Forget" },
  { id: 259, clue: `3D`, answer: "Third Dimension" },
  { id: 260, clue: `8 ATE 8`, answer: "Piece of cake" },
  { id: 261, clue: `B-SIDE`, answer: "Beside" },
  { id: 262, clue: `C-LEVEL`, answer: "Sea level" },
  { id: 263, clue: `G-STRING`, answer: "G-string" },
  { id: 264, clue: `T-BONE`, answer: "T-bone" },
  { id: 265, clue: `X-RAY`, answer: "X-ray" },
  { id: 266, clue: `P-POD`, answer: "Peas in a pod" },
  { id: 267, clue: `K-9`, answer: "Canine" },
  { id: 268, clue: `B-LINE`, answer: "Beeline" },
  { id: 269, clue: `Q-TIP`, answer: "Q-tip" },
  { id: 270, clue: `U-TURN`, answer: "U-turn" },
  { id: 271, clue: `I-OPENER`, answer: "Eye opener" },
  { id: 272, clue: `T-TIME`, answer: "Tea time" },
  { id: 273, clue: `E-MAIL`, answer: "Email" },
  { id: 274, clue: `B-BALL`, answer: "Basketball" },
  { id: 275, clue: `J-WALK`, answer: "Jaywalk" },
  { id: 276, clue: `C-SHORE`, answer: "Seashore" },
  { id: 277, clue: `U-BOAT`, answer: "U-boat" },
  { id: 278, clue: `V-NECK`, answer: "V-neck" },
  { id: 279, clue: `S-CAPE`, answer: "Escape" },
  { id: 280, clue: `B-STING`, answer: "Bee sting" },
  { id: 281, clue: `T-SHIRT`, answer: "T-shirt" },
  { id: 282, clue: `B-READY`, answer: "Be ready" },
  { id: 283, clue: `P-SOUP`, answer: "Pea soup" },
  { id: 284, clue: `I-LAND`, answer: "Island" },
  { id: 285, clue: `X-CHANGE`, answer: "Exchange" },
  { id: 286, clue: `T-LIGHT`, answer: "Tea light" },
  { id: 287, clue: `C-FOOD`, answer: "Seafood" },
  { id: 288, clue: `B-COOL`, answer: "Be cool" },
  { id: 289, clue: `G-FORCE`, answer: "G-force" },
  { id: 290, clue: `T-BAG`, answer: "Tea bag" },
  { id: 291, clue: `P-NUT`, answer: "Peanut" },
  { id: 292, clue: `B-HAVE`, answer: "Behave" },
  { id: 293, clue: `X-PRESS`, answer: "Express" },
  { id: 294, clue: `O-RING`, answer: "O-ring" },
  { id: 295, clue: `C-SAW`, answer: "Seasaw" },
  { id: 296, clue: `B-HIND`, answer: "Behind" },
  { id: 297, clue: `T-POT`, answer: "Teapot" },
  { id: 298, clue: `G-UNIT`, answer: "G-unit" },
  { id: 299, clue: `A-LIST`, answer: "A-list" },
  { id: 300, clue: `C-SIDE`, answer: "Seaside" },
  { id: 301, clue: `MAN
BOARD`, answer: "Man Overboard" },
  { id: 302, clue: `STAND
—————
I`, answer: "I Understand" },
  { id: 303, clue: `THOUGHT`, answer: "Deep Thought" },
  { id: 304, clue: `R
E
A
D`, answer: "Read Up" },
  { id: 305, clue: `KNEE
LIGHTS`, answer: "Neon Lights" },
  { id: 306, clue: `ii ii`, answer: "See eye to eye" },
  { id: 307, clue: `TIMING TIMING`, answer: "Double Timing" },
  { id: 308, clue: `WAY
—————
S`, answer: "Subway" },
  { id: 309, clue: `LE
VEL`, answer: "Split Level" },
  { id: 310, clue: `DICE
DICE`, answer: "Paradise" },
  { id: 311, clue: `MCE MCE MCE`, answer: "Three Blind Mice" },
  { id: 312, clue: `LONG
WEAR`, answer: "Long Underwear" },
  { id: 313, clue: `HEAD
HEELS`, answer: "Head Over Heels" },
  { id: 314, clue: `CHART`, answer: "Off the Charts" },
  { id: 315, clue: `HISTORY HISTORY
HISTORY`, answer: "History repeats itself" },
  { id: 316, clue: `SYMPHON...`, answer: "Unfinished Symphony" },
  { id: 317, clue: `WOLF`, answer: "Wolf in sheep's clothing" },
  { id: 318, clue: `GIVE GIVE GIVE GIVE
GET GET GET GET`, answer: "Forgive and Forget" },
  { id: 319, clue: `ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE`, answer: "Tennis Shoes (Ten-issue)" },
  { id: 320, clue: `X Q Q Q ME`, answer: "Excuse Me" },
  { id: 321, clue: `HE'S/HIMSELF`, answer: "He's beside himself" },
  { id: 322, clue: `YOU ME`, answer: "Just between you and me" },
  { id: 323, clue: `TTTTTTTT`, answer: "Tea for two (T for 2)" },
  { id: 324, clue: `BUS`, answer: "Business" },
  { id: 325, clue: `PIPPED`, answer: "Pipped at the post" },
  { id: 326, clue: `EGG EGG`, answer: "Two eggs over easy" },
  { id: 327, clue: `PUNISHMENT`, answer: "Capital Punishment" },
  { id: 328, clue: `TOWN`, answer: "Man about town" },
  { id: 329, clue: `SEARCH
AND`, answer: "Search high and low" },
  { id: 330, clue: `FEET FEET FEET FEET
FEET FEET`, answer: "Six feet under" },
  { id: 331, clue: `NOON`, answer: "High Noon" },
  { id: 332, clue: `FALLING
LOVE`, answer: "Falling in love" },
  { id: 333, clue: `AGE`, answer: "Middle Age" },
  { id: 334, clue: `ROADS`, answer: "Crossroads" },
  { id: 335, clue: `MIND
MATTER`, answer: "Mind over matter" },
  { id: 336, clue: `KISS`, answer: "A big kiss" },
  { id: 337, clue: `TIME`, answer: "Time is up" },
  { id: 338, clue: `GROUND`, answer: "Six feet under ground" },
  { id: 339, clue: `CYCLE CYCLE CYCLE`, answer: "Tricycle" },
  { id: 340, clue: `DEAL`, answer: "Big Deal" },
  { id: 341, clue: `STOD`, answer: "Backwards" },
  { id: 342, clue: `POLICE`, answer: "Police on your tail" },
  { id: 343, clue: `LUCK`, answer: "Stroke of luck" },
  { id: 344, clue: `WEATHER`, answer: "Under the weather" },
  { id: 345, clue: `HEART`, answer: "Heart in the right place" },
  { id: 346, clue: `EYE`, answer: "Eye on the ball" },
  { id: 347, clue: `LIFE`, answer: "Life after death" },
  { id: 348, clue: `FRIENDS`, answer: "Friends in high places" },
  { id: 349, clue: `O_ER_T_O_`, answer: "Painless Operation" },
  { id: 350, clue: `TOUCH`, answer: "Touchdown" },
  { id: 351, clue: `VA DERS`, answer: "Space Invaders" },
  { id: 352, clue: `CHANCE`, answer: "Slim Chance" },
  { id: 353, clue: `BIRD`, answer: "Early Bird" },
  { id: 354, clue: `SECRET`, answer: "Top Secret" },
  { id: 355, clue: `PAINSTOP`, answer: "Stop and think" },
  { id: 356, clue: `JOB`, answer: "In between jobs" },
  { id: 357, clue: `GAGES`, answer: "Engages" },
  { id: 358, clue: `4GET`, answer: "Forget" },
  { id: 359, clue: `3D`, answer: "Third Dimension" },
  { id: 360, clue: `8 ATE 8`, answer: "Piece of cake" },
  { id: 361, clue: `B-SIDE`, answer: "Beside" },
  { id: 362, clue: `C-LEVEL`, answer: "Sea level" },
  { id: 363, clue: `G-STRING`, answer: "G-string" },
  { id: 364, clue: `T-BONE`, answer: "T-bone" },
  { id: 365, clue: `X-RAY`, answer: "X-ray" },
  { id: 366, clue: `P-POD`, answer: "Peas in a pod" },
  { id: 367, clue: `K-9`, answer: "Canine" },
  { id: 368, clue: `B-LINE`, answer: "Beeline" },
  { id: 369, clue: `Q-TIP`, answer: "Q-tip" },
  { id: 370, clue: `U-TURN`, answer: "U-turn" },
  { id: 371, clue: `I-OPENER`, answer: "Eye opener" },
  { id: 372, clue: `T-TIME`, answer: "Tea time" },
  { id: 373, clue: `E-MAIL`, answer: "Email" },
  { id: 374, clue: `B-BALL`, answer: "Basketball" },
  { id: 375, clue: `J-WALK`, answer: "Jaywalk" },
  { id: 376, clue: `C-SHORE`, answer: "Seashore" },
  { id: 377, clue: `U-BOAT`, answer: "U-boat" },
  { id: 378, clue: `V-NECK`, answer: "V-neck" },
  { id: 379, clue: `S-CAPE`, answer: "Escape" },
  { id: 380, clue: `B-STING`, answer: "Bee sting" },
  { id: 381, clue: `T-SHIRT`, answer: "T-shirt" },
  { id: 382, clue: `B-READY`, answer: "Be ready" },
  { id: 383, clue: `P-SOUP`, answer: "Pea soup" },
  { id: 384, clue: `I-LAND`, answer: "Island" },
  { id: 385, clue: `X-CHANGE`, answer: "Exchange" },
  { id: 386, clue: `T-LIGHT`, answer: "Tea light" },
  { id: 387, clue: `C-FOOD`, answer: "Seafood" },
  { id: 388, clue: `B-COOL`, answer: "Be cool" },
  { id: 389, clue: `G-FORCE`, answer: "G-force" },
  { id: 390, clue: `T-BAG`, answer: "Tea bag" },
  { id: 391, clue: `P-NUT`, answer: "Peanut" },
  { id: 392, clue: `B-HAVE`, answer: "Behave" },
  { id: 393, clue: `X-PRESS`, answer: "Express" },
  { id: 394, clue: `O-RING`, answer: "O-ring" },
  { id: 395, clue: `C-SAW`, answer: "Seasaw" },
  { id: 396, clue: `B-HIND`, answer: "Behind" },
  { id: 397, clue: `T-POT`, answer: "Teapot" },
  { id: 398, clue: `G-UNIT`, answer: "G-unit" },
  { id: 399, clue: `A-LIST`, answer: "A-list" },
  { id: 400, clue: `C-SIDE`, answer: "Seaside" },
  { id: 401, clue: `MAN
BOARD`, answer: "Man Overboard" },
  { id: 402, clue: `STAND
—————
I`, answer: "I Understand" },
  { id: 403, clue: `THOUGHT`, answer: "Deep Thought" },
  { id: 404, clue: `R
E
A
D`, answer: "Read Up" },
  { id: 405, clue: `KNEE
LIGHTS`, answer: "Neon Lights" },
  { id: 406, clue: `ii ii`, answer: "See eye to eye" },
  { id: 407, clue: `TIMING TIMING`, answer: "Double Timing" },
  { id: 408, clue: `WAY
—————
S`, answer: "Subway" },
  { id: 409, clue: `LE
VEL`, answer: "Split Level" },
  { id: 410, clue: `DICE
DICE`, answer: "Paradise" },
  { id: 411, clue: `MCE MCE MCE`, answer: "Three Blind Mice" },
  { id: 412, clue: `LONG
WEAR`, answer: "Long Underwear" },
  { id: 413, clue: `HEAD
HEELS`, answer: "Head Over Heels" },
  { id: 414, clue: `CHART`, answer: "Off the Charts" },
  { id: 415, clue: `HISTORY HISTORY
HISTORY`, answer: "History repeats itself" },
  { id: 416, clue: `SYMPHON...`, answer: "Unfinished Symphony" },
  { id: 417, clue: `WOLF`, answer: "Wolf in sheep's clothing" },
  { id: 418, clue: `GIVE GIVE GIVE GIVE
GET GET GET GET`, answer: "Forgive and Forget" },
  { id: 419, clue: `ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE`, answer: "Tennis Shoes (Ten-issue)" },
  { id: 420, clue: `X Q Q Q ME`, answer: "Excuse Me" },
  { id: 421, clue: `HE'S/HIMSELF`, answer: "He's beside himself" },
  { id: 422, clue: `YOU ME`, answer: "Just between you and me" },
  { id: 423, clue: `TTTTTTTT`, answer: "Tea for two (T for 2)" },
  { id: 424, clue: `BUS`, answer: "Business" },
  { id: 425, clue: `PIPPED`, answer: "Pipped at the post" },
  { id: 426, clue: `EGG EGG`, answer: "Two eggs over easy" },
  { id: 427, clue: `PUNISHMENT`, answer: "Capital Punishment" },
  { id: 428, clue: `TOWN`, answer: "Man about town" },
  { id: 429, clue: `SEARCH
AND`, answer: "Search high and low" },
  { id: 430, clue: `FEET FEET FEET FEET
FEET FEET`, answer: "Six feet under" },
  { id: 431, clue: `NOON`, answer: "High Noon" },
  { id: 432, clue: `FALLING
LOVE`, answer: "Falling in love" },
  { id: 433, clue: `AGE`, answer: "Middle Age" },
  { id: 434, clue: `ROADS`, answer: "Crossroads" },
  { id: 435, clue: `MIND
MATTER`, answer: "Mind over matter" },
  { id: 436, clue: `KISS`, answer: "A big kiss" },
  { id: 437, clue: `TIME`, answer: "Time is up" },
  { id: 438, clue: `GROUND`, answer: "Six feet under ground" },
  { id: 439, clue: `CYCLE CYCLE CYCLE`, answer: "Tricycle" },
  { id: 440, clue: `DEAL`, answer: "Big Deal" },
  { id: 441, clue: `STOD`, answer: "Backwards" },
  { id: 442, clue: `POLICE`, answer: "Police on your tail" },
  { id: 443, clue: `LUCK`, answer: "Stroke of luck" },
  { id: 444, clue: `WEATHER`, answer: "Under the weather" },
  { id: 445, clue: `HEART`, answer: "Heart in the right place" },
  { id: 446, clue: `EYE`, answer: "Eye on the ball" },
  { id: 447, clue: `LIFE`, answer: "Life after death" },
  { id: 448, clue: `FRIENDS`, answer: "Friends in high places" },
  { id: 449, clue: `O_ER_T_O_`, answer: "Painless Operation" },
  { id: 450, clue: `TOUCH`, answer: "Touchdown" },
  { id: 451, clue: `VA DERS`, answer: "Space Invaders" },
  { id: 452, clue: `CHANCE`, answer: "Slim Chance" },
  { id: 453, clue: `BIRD`, answer: "Early Bird" },
  { id: 454, clue: `SECRET`, answer: "Top Secret" },
  { id: 455, clue: `PAINSTOP`, answer: "Stop and think" },
  { id: 456, clue: `JOB`, answer: "In between jobs" },
  { id: 457, clue: `GAGES`, answer: "Engages" },
  { id: 458, clue: `4GET`, answer: "Forget" },
  { id: 459, clue: `3D`, answer: "Third Dimension" },
  { id: 460, clue: `8 ATE 8`, answer: "Piece of cake" },
  { id: 461, clue: `B-SIDE`, answer: "Beside" },
  { id: 462, clue: `C-LEVEL`, answer: "Sea level" },
  { id: 463, clue: `G-STRING`, answer: "G-string" },
  { id: 464, clue: `T-BONE`, answer: "T-bone" },
  { id: 465, clue: `X-RAY`, answer: "X-ray" },
  { id: 466, clue: `P-POD`, answer: "Peas in a pod" },
  { id: 467, clue: `K-9`, answer: "Canine" },
  { id: 468, clue: `B-LINE`, answer: "Beeline" },
  { id: 469, clue: `Q-TIP`, answer: "Q-tip" },
  { id: 470, clue: `U-TURN`, answer: "U-turn" },
  { id: 471, clue: `I-OPENER`, answer: "Eye opener" },
  { id: 472, clue: `T-TIME`, answer: "Tea time" },
  { id: 473, clue: `E-MAIL`, answer: "Email" },
  { id: 474, clue: `B-BALL`, answer: "Basketball" },
  { id: 475, clue: `J-WALK`, answer: "Jaywalk" },
  { id: 476, clue: `C-SHORE`, answer: "Seashore" },
  { id: 477, clue: `U-BOAT`, answer: "U-boat" },
  { id: 478, clue: `V-NECK`, answer: "V-neck" },
  { id: 479, clue: `S-CAPE`, answer: "Escape" },
  { id: 480, clue: `B-STING`, answer: "Bee sting" },
  { id: 481, clue: `T-SHIRT`, answer: "T-shirt" },
  { id: 482, clue: `B-READY`, answer: "Be ready" },
  { id: 483, clue: `P-SOUP`, answer: "Pea soup" },
  { id: 484, clue: `I-LAND`, answer: "Island" },
  { id: 485, clue: `X-CHANGE`, answer: "Exchange" },
  { id: 486, clue: `T-LIGHT`, answer: "Tea light" },
  { id: 487, clue: `C-FOOD`, answer: "Seafood" },
  { id: 488, clue: `B-COOL`, answer: "Be cool" },
  { id: 489, clue: `G-FORCE`, answer: "G-force" },
  { id: 490, clue: `T-BAG`, answer: "Tea bag" },
  { id: 491, clue: `P-NUT`, answer: "Peanut" },
  { id: 492, clue: `B-HAVE`, answer: "Behave" },
  { id: 493, clue: `X-PRESS`, answer: "Express" },
  { id: 494, clue: `O-RING`, answer: "O-ring" },
  { id: 495, clue: `C-SAW`, answer: "Seasaw" },
  { id: 496, clue: `B-HIND`, answer: "Behind" },
  { id: 497, clue: `T-POT`, answer: "Teapot" },
  { id: 498, clue: `G-UNIT`, answer: "G-unit" },
  { id: 499, clue: `A-LIST`, answer: "A-list" },
  { id: 500, clue: `C-SIDE`, answer: "Seaside" },
  { id: 501, clue: `MAN
BOARD`, answer: "Man Overboard" },
  { id: 502, clue: `STAND
—————
I`, answer: "I Understand" },
  { id: 503, clue: `THOUGHT`, answer: "Deep Thought" },
  { id: 504, clue: `R
E
A
D`, answer: "Read Up" },
  { id: 505, clue: `KNEE
LIGHTS`, answer: "Neon Lights" },
  { id: 506, clue: `ii ii`, answer: "See eye to eye" },
  { id: 507, clue: `TIMING TIMING`, answer: "Double Timing" },
  { id: 508, clue: `WAY
—————
S`, answer: "Subway" },
  { id: 509, clue: `LE
VEL`, answer: "Split Level" },
  { id: 510, clue: `DICE
DICE`, answer: "Paradise" },
  { id: 511, clue: `MCE MCE MCE`, answer: "Three Blind Mice" },
  { id: 512, clue: `LONG
WEAR`, answer: "Long Underwear" },
  { id: 513, clue: `HEAD
HEELS`, answer: "Head Over Heels" },
  { id: 514, clue: `CHART`, answer: "Off the Charts" },
  { id: 515, clue: `HISTORY HISTORY
HISTORY`, answer: "History repeats itself" },
  { id: 516, clue: `SYMPHON...`, answer: "Unfinished Symphony" },
  { id: 517, clue: `WOLF`, answer: "Wolf in sheep's clothing" },
  { id: 518, clue: `GIVE GIVE GIVE GIVE
GET GET GET GET`, answer: "Forgive and Forget" },
  { id: 519, clue: `ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE`, answer: "Tennis Shoes (Ten-issue)" },
  { id: 520, clue: `X Q Q Q ME`, answer: "Excuse Me" },
  { id: 521, clue: `HE'S/HIMSELF`, answer: "He's beside himself" },
  { id: 522, clue: `YOU ME`, answer: "Just between you and me" },
  { id: 523, clue: `TTTTTTTT`, answer: "Tea for two (T for 2)" },
  { id: 524, clue: `BUS`, answer: "Business" },
  { id: 525, clue: `PIPPED`, answer: "Pipped at the post" },
  { id: 526, clue: `EGG EGG`, answer: "Two eggs over easy" },
  { id: 527, clue: `PUNISHMENT`, answer: "Capital Punishment" },
  { id: 528, clue: `TOWN`, answer: "Man about town" },
  { id: 529, clue: `SEARCH
AND`, answer: "Search high and low" },
  { id: 530, clue: `FEET FEET FEET FEET
FEET FEET`, answer: "Six feet under" },
  { id: 531, clue: `NOON`, answer: "High Noon" },
  { id: 532, clue: `FALLING
LOVE`, answer: "Falling in love" },
  { id: 533, clue: `AGE`, answer: "Middle Age" },
  { id: 534, clue: `ROADS`, answer: "Crossroads" },
  { id: 535, clue: `MIND
MATTER`, answer: "Mind over matter" },
  { id: 536, clue: `KISS`, answer: "A big kiss" },
  { id: 537, clue: `TIME`, answer: "Time is up" },
  { id: 538, clue: `GROUND`, answer: "Six feet under ground" },
  { id: 539, clue: `CYCLE CYCLE CYCLE`, answer: "Tricycle" },
  { id: 540, clue: `DEAL`, answer: "Big Deal" },
  { id: 541, clue: `STOD`, answer: "Backwards" },
  { id: 542, clue: `POLICE`, answer: "Police on your tail" },
  { id: 543, clue: `LUCK`, answer: "Stroke of luck" },
  { id: 544, clue: `WEATHER`, answer: "Under the weather" },
  { id: 545, clue: `HEART`, answer: "Heart in the right place" },
  { id: 546, clue: `EYE`, answer: "Eye on the ball" },
  { id: 547, clue: `LIFE`, answer: "Life after death" },
  { id: 548, clue: `FRIENDS`, answer: "Friends in high places" },
  { id: 549, clue: `O_ER_T_O_`, answer: "Painless Operation" },
  { id: 550, clue: `TOUCH`, answer: "Touchdown" },
  { id: 551, clue: `VA DERS`, answer: "Space Invaders" },
  { id: 552, clue: `CHANCE`, answer: "Slim Chance" },
  { id: 553, clue: `BIRD`, answer: "Early Bird" },
  { id: 554, clue: `SECRET`, answer: "Top Secret" },
  { id: 555, clue: `PAINSTOP`, answer: "Stop and think" },
  { id: 556, clue: `JOB`, answer: "In between jobs" },
  { id: 557, clue: `GAGES`, answer: "Engages" },
  { id: 558, clue: `4GET`, answer: "Forget" },
  { id: 559, clue: `3D`, answer: "Third Dimension" },
  { id: 560, clue: `8 ATE 8`, answer: "Piece of cake" },
  { id: 561, clue: `B-SIDE`, answer: "Beside" },
  { id: 562, clue: `C-LEVEL`, answer: "Sea level" },
  { id: 563, clue: `G-STRING`, answer: "G-string" },
  { id: 564, clue: `T-BONE`, answer: "T-bone" },
  { id: 565, clue: `X-RAY`, answer: "X-ray" },
  { id: 566, clue: `P-POD`, answer: "Peas in a pod" },
  { id: 567, clue: `K-9`, answer: "Canine" },
  { id: 568, clue: `B-LINE`, answer: "Beeline" },
  { id: 569, clue: `Q-TIP`, answer: "Q-tip" },
  { id: 570, clue: `U-TURN`, answer: "U-turn" },
  { id: 571, clue: `I-OPENER`, answer: "Eye opener" },
  { id: 572, clue: `T-TIME`, answer: "Tea time" },
  { id: 573, clue: `E-MAIL`, answer: "Email" },
  { id: 574, clue: `B-BALL`, answer: "Basketball" },
  { id: 575, clue: `J-WALK`, answer: "Jaywalk" },
  { id: 576, clue: `C-SHORE`, answer: "Seashore" },
  { id: 577, clue: `U-BOAT`, answer: "U-boat" },
  { id: 578, clue: `V-NECK`, answer: "V-neck" },
  { id: 579, clue: `S-CAPE`, answer: "Escape" },
  { id: 580, clue: `B-STING`, answer: "Bee sting" },
  { id: 581, clue: `T-SHIRT`, answer: "T-shirt" },
  { id: 582, clue: `B-READY`, answer: "Be ready" },
  { id: 583, clue: `P-SOUP`, answer: "Pea soup" },
  { id: 584, clue: `I-LAND`, answer: "Island" },
  { id: 585, clue: `X-CHANGE`, answer: "Exchange" },
  { id: 586, clue: `T-LIGHT`, answer: "Tea light" },
  { id: 587, clue: `C-FOOD`, answer: "Seafood" },
  { id: 588, clue: `B-COOL`, answer: "Be cool" },
  { id: 589, clue: `G-FORCE`, answer: "G-force" },
  { id: 590, clue: `T-BAG`, answer: "Tea bag" },
  { id: 591, clue: `P-NUT`, answer: "Peanut" },
  { id: 592, clue: `B-HAVE`, answer: "Behave" },
  { id: 593, clue: `X-PRESS`, answer: "Express" },
  { id: 594, clue: `O-RING`, answer: "O-ring" },
  { id: 595, clue: `C-SAW`, answer: "Seasaw" },
  { id: 596, clue: `B-HIND`, answer: "Behind" },
  { id: 597, clue: `T-POT`, answer: "Teapot" },
  { id: 598, clue: `G-UNIT`, answer: "G-unit" },
  { id: 599, clue: `A-LIST`, answer: "A-list" },
  { id: 600, clue: `C-SIDE`, answer: "Seaside" },
  { id: 601, clue: `MAN
BOARD`, answer: "Man Overboard" },
  { id: 602, clue: `STAND
—————
I`, answer: "I Understand" },
  { id: 603, clue: `THOUGHT`, answer: "Deep Thought" },
  { id: 604, clue: `R
E
A
D`, answer: "Read Up" },
  { id: 605, clue: `KNEE
LIGHTS`, answer: "Neon Lights" },
  { id: 606, clue: `ii ii`, answer: "See eye to eye" },
  { id: 607, clue: `TIMING TIMING`, answer: "Double Timing" },
  { id: 608, clue: `WAY
—————
S`, answer: "Subway" },
  { id: 609, clue: `LE
VEL`, answer: "Split Level" },
  { id: 610, clue: `DICE
DICE`, answer: "Paradise" },
  { id: 611, clue: `MCE MCE MCE`, answer: "Three Blind Mice" },
  { id: 612, clue: `LONG
WEAR`, answer: "Long Underwear" },
  { id: 613, clue: `HEAD
HEELS`, answer: "Head Over Heels" },
  { id: 614, clue: `CHART`, answer: "Off the Charts" },
  { id: 615, clue: `HISTORY HISTORY
HISTORY`, answer: "History repeats itself" },
  { id: 616, clue: `SYMPHON...`, answer: "Unfinished Symphony" },
  { id: 617, clue: `WOLF`, answer: "Wolf in sheep's clothing" },
  { id: 618, clue: `GIVE GIVE GIVE GIVE
GET GET GET GET`, answer: "Forgive and Forget" },
  { id: 619, clue: `ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE`, answer: "Tennis Shoes (Ten-issue)" },
  { id: 620, clue: `X Q Q Q ME`, answer: "Excuse Me" },
  { id: 621, clue: `HE'S/HIMSELF`, answer: "He's beside himself" },
  { id: 622, clue: `YOU ME`, answer: "Just between you and me" },
  { id: 623, clue: `TTTTTTTT`, answer: "Tea for two (T for 2)" },
  { id: 624, clue: `BUS`, answer: "Business" },
  { id: 625, clue: `PIPPED`, answer: "Pipped at the post" },
  { id: 626, clue: `EGG EGG`, answer: "Two eggs over easy" },
  { id: 627, clue: `PUNISHMENT`, answer: "Capital Punishment" },
  { id: 628, clue: `TOWN`, answer: "Man about town" },
  { id: 629, clue: `SEARCH
AND`, answer: "Search high and low" },
  { id: 630, clue: `FEET FEET FEET FEET
FEET FEET`, answer: "Six feet under" },
  { id: 631, clue: `NOON`, answer: "High Noon" },
  { id: 632, clue: `FALLING
LOVE`, answer: "Falling in love" },
  { id: 633, clue: `AGE`, answer: "Middle Age" },
  { id: 634, clue: `ROADS`, answer: "Crossroads" },
  { id: 635, clue: `MIND
MATTER`, answer: "Mind over matter" },
  { id: 636, clue: `KISS`, answer: "A big kiss" },
  { id: 637, clue: `TIME`, answer: "Time is up" },
  { id: 638, clue: `GROUND`, answer: "Six feet under ground" },
  { id: 639, clue: `CYCLE CYCLE CYCLE`, answer: "Tricycle" },
  { id: 640, clue: `DEAL`, answer: "Big Deal" },
  { id: 641, clue: `STOD`, answer: "Backwards" },
  { id: 642, clue: `POLICE`, answer: "Police on your tail" },
  { id: 643, clue: `LUCK`, answer: "Stroke of luck" },
  { id: 644, clue: `WEATHER`, answer: "Under the weather" },
  { id: 645, clue: `HEART`, answer: "Heart in the right place" },
  { id: 646, clue: `EYE`, answer: "Eye on the ball" },
  { id: 647, clue: `LIFE`, answer: "Life after death" },
  { id: 648, clue: `FRIENDS`, answer: "Friends in high places" },
  { id: 649, clue: `O_ER_T_O_`, answer: "Painless Operation" },
  { id: 650, clue: `TOUCH`, answer: "Touchdown" },
  { id: 651, clue: `VA DERS`, answer: "Space Invaders" },
  { id: 652, clue: `CHANCE`, answer: "Slim Chance" },
  { id: 653, clue: `BIRD`, answer: "Early Bird" },
  { id: 654, clue: `SECRET`, answer: "Top Secret" },
  { id: 655, clue: `PAINSTOP`, answer: "Stop and think" },
  { id: 656, clue: `JOB`, answer: "In between jobs" },
  { id: 657, clue: `GAGES`, answer: "Engages" },
  { id: 658, clue: `4GET`, answer: "Forget" },
  { id: 659, clue: `3D`, answer: "Third Dimension" },
  { id: 660, clue: `8 ATE 8`, answer: "Piece of cake" },
  { id: 661, clue: `B-SIDE`, answer: "Beside" },
  { id: 662, clue: `C-LEVEL`, answer: "Sea level" },
  { id: 663, clue: `G-STRING`, answer: "G-string" },
  { id: 664, clue: `T-BONE`, answer: "T-bone" },
  { id: 665, clue: `X-RAY`, answer: "X-ray" },
  { id: 666, clue: `P-POD`, answer: "Peas in a pod" },
  { id: 667, clue: `K-9`, answer: "Canine" },
  { id: 668, clue: `B-LINE`, answer: "Beeline" },
  { id: 669, clue: `Q-TIP`, answer: "Q-tip" },
  { id: 670, clue: `U-TURN`, answer: "U-turn" },
  { id: 671, clue: `I-OPENER`, answer: "Eye opener" },
  { id: 672, clue: `T-TIME`, answer: "Tea time" },
  { id: 673, clue: `E-MAIL`, answer: "Email" },
  { id: 674, clue: `B-BALL`, answer: "Basketball" },
  { id: 675, clue: `J-WALK`, answer: "Jaywalk" },
  { id: 676, clue: `C-SHORE`, answer: "Seashore" },
  { id: 677, clue: `U-BOAT`, answer: "U-boat" },
  { id: 678, clue: `V-NECK`, answer: "V-neck" },
  { id: 679, clue: `S-CAPE`, answer: "Escape" },
  { id: 680, clue: `B-STING`, answer: "Bee sting" },
  { id: 681, clue: `T-SHIRT`, answer: "T-shirt" },
  { id: 682, clue: `B-READY`, answer: "Be ready" },
  { id: 683, clue: `P-SOUP`, answer: "Pea soup" },
  { id: 684, clue: `I-LAND`, answer: "Island" },
  { id: 685, clue: `X-CHANGE`, answer: "Exchange" },
  { id: 686, clue: `T-LIGHT`, answer: "Tea light" },
  { id: 687, clue: `C-FOOD`, answer: "Seafood" },
  { id: 688, clue: `B-COOL`, answer: "Be cool" },
  { id: 689, clue: `G-FORCE`, answer: "G-force" },
  { id: 690, clue: `T-BAG`, answer: "Tea bag" },
  { id: 691, clue: `P-NUT`, answer: "Peanut" },
  { id: 692, clue: `B-HAVE`, answer: "Behave" },
  { id: 693, clue: `X-PRESS`, answer: "Express" },
  { id: 694, clue: `O-RING`, answer: "O-ring" },
  { id: 695, clue: `C-SAW`, answer: "Seasaw" },
  { id: 696, clue: `B-HIND`, answer: "Behind" },
  { id: 697, clue: `T-POT`, answer: "Teapot" },
  { id: 698, clue: `G-UNIT`, answer: "G-unit" },
  { id: 699, clue: `A-LIST`, answer: "A-list" },
  { id: 700, clue: `C-SIDE`, answer: "Seaside" },
  { id: 701, clue: `MAN
BOARD`, answer: "Man Overboard" },
  { id: 702, clue: `STAND
—————
I`, answer: "I Understand" },
  { id: 703, clue: `THOUGHT`, answer: "Deep Thought" },
  { id: 704, clue: `R
E
A
D`, answer: "Read Up" },
  { id: 705, clue: `KNEE
LIGHTS`, answer: "Neon Lights" },
  { id: 706, clue: `ii ii`, answer: "See eye to eye" },
  { id: 707, clue: `TIMING TIMING`, answer: "Double Timing" },
  { id: 708, clue: `WAY
—————
S`, answer: "Subway" },
  { id: 709, clue: `LE
VEL`, answer: "Split Level" },
  { id: 710, clue: `DICE
DICE`, answer: "Paradise" },
  { id: 711, clue: `MCE MCE MCE`, answer: "Three Blind Mice" },
  { id: 712, clue: `LONG
WEAR`, answer: "Long Underwear" },
  { id: 713, clue: `HEAD
HEELS`, answer: "Head Over Heels" },
  { id: 714, clue: `CHART`, answer: "Off the Charts" },
  { id: 715, clue: `HISTORY HISTORY
HISTORY`, answer: "History repeats itself" },
  { id: 716, clue: `SYMPHON...`, answer: "Unfinished Symphony" },
  { id: 717, clue: `WOLF`, answer: "Wolf in sheep's clothing" },
  { id: 718, clue: `GIVE GIVE GIVE GIVE
GET GET GET GET`, answer: "Forgive and Forget" },
  { id: 719, clue: `ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE`, answer: "Tennis Shoes (Ten-issue)" },
  { id: 720, clue: `X Q Q Q ME`, answer: "Excuse Me" },
  { id: 721, clue: `HE'S/HIMSELF`, answer: "He's beside himself" },
  { id: 722, clue: `YOU ME`, answer: "Just between you and me" },
  { id: 723, clue: `TTTTTTTT`, answer: "Tea for two (T for 2)" },
  { id: 724, clue: `BUS`, answer: "Business" },
  { id: 725, clue: `PIPPED`, answer: "Pipped at the post" },
  { id: 726, clue: `EGG EGG`, answer: "Two eggs over easy" },
  { id: 727, clue: `PUNISHMENT`, answer: "Capital Punishment" },
  { id: 728, clue: `TOWN`, answer: "Man about town" },
  { id: 729, clue: `SEARCH
AND`, answer: "Search high and low" },
  { id: 730, clue: `FEET FEET FEET FEET
FEET FEET`, answer: "Six feet under" },
  { id: 731, clue: `NOON`, answer: "High Noon" },
  { id: 732, clue: `FALLING
LOVE`, answer: "Falling in love" },
  { id: 733, clue: `AGE`, answer: "Middle Age" },
  { id: 734, clue: `ROADS`, answer: "Crossroads" },
  { id: 735, clue: `MIND
MATTER`, answer: "Mind over matter" },
  { id: 736, clue: `KISS`, answer: "A big kiss" },
  { id: 737, clue: `TIME`, answer: "Time is up" },
  { id: 738, clue: `GROUND`, answer: "Six feet under ground" },
  { id: 739, clue: `CYCLE CYCLE CYCLE`, answer: "Tricycle" },
  { id: 740, clue: `DEAL`, answer: "Big Deal" },
  { id: 741, clue: `STOD`, answer: "Backwards" },
  { id: 742, clue: `POLICE`, answer: "Police on your tail" },
  { id: 743, clue: `LUCK`, answer: "Stroke of luck" },
  { id: 744, clue: `WEATHER`, answer: "Under the weather" },
  { id: 745, clue: `HEART`, answer: "Heart in the right place" },
  { id: 746, clue: `EYE`, answer: "Eye on the ball" },
  { id: 747, clue: `LIFE`, answer: "Life after death" },
  { id: 748, clue: `FRIENDS`, answer: "Friends in high places" },
  { id: 749, clue: `O_ER_T_O_`, answer: "Painless Operation" },
  { id: 750, clue: `TOUCH`, answer: "Touchdown" },
  { id: 751, clue: `VA DERS`, answer: "Space Invaders" },
  { id: 752, clue: `CHANCE`, answer: "Slim Chance" },
  { id: 753, clue: `BIRD`, answer: "Early Bird" },
  { id: 754, clue: `SECRET`, answer: "Top Secret" },
  { id: 755, clue: `PAINSTOP`, answer: "Stop and think" },
  { id: 756, clue: `JOB`, answer: "In between jobs" },
  { id: 757, clue: `GAGES`, answer: "Engages" },
  { id: 758, clue: `4GET`, answer: "Forget" },
  { id: 759, clue: `3D`, answer: "Third Dimension" },
  { id: 760, clue: `8 ATE 8`, answer: "Piece of cake" },
  { id: 761, clue: `B-SIDE`, answer: "Beside" },
  { id: 762, clue: `C-LEVEL`, answer: "Sea level" },
  { id: 763, clue: `G-STRING`, answer: "G-string" },
  { id: 764, clue: `T-BONE`, answer: "T-bone" },
  { id: 765, clue: `X-RAY`, answer: "X-ray" },
  { id: 766, clue: `P-POD`, answer: "Peas in a pod" },
  { id: 767, clue: `K-9`, answer: "Canine" },
  { id: 768, clue: `B-LINE`, answer: "Beeline" },
  { id: 769, clue: `Q-TIP`, answer: "Q-tip" },
  { id: 770, clue: `U-TURN`, answer: "U-turn" },
  { id: 771, clue: `I-OPENER`, answer: "Eye opener" },
  { id: 772, clue: `T-TIME`, answer: "Tea time" },
  { id: 773, clue: `E-MAIL`, answer: "Email" },
  { id: 774, clue: `B-BALL`, answer: "Basketball" },
  { id: 775, clue: `J-WALK`, answer: "Jaywalk" },
  { id: 776, clue: `C-SHORE`, answer: "Seashore" },
  { id: 777, clue: `U-BOAT`, answer: "U-boat" },
  { id: 778, clue: `V-NECK`, answer: "V-neck" },
  { id: 779, clue: `S-CAPE`, answer: "Escape" },
  { id: 780, clue: `B-STING`, answer: "Bee sting" },
  { id: 781, clue: `T-SHIRT`, answer: "T-shirt" },
  { id: 782, clue: `B-READY`, answer: "Be ready" },
  { id: 783, clue: `P-SOUP`, answer: "Pea soup" },
  { id: 784, clue: `I-LAND`, answer: "Island" },
  { id: 785, clue: `X-CHANGE`, answer: "Exchange" },
  { id: 786, clue: `T-LIGHT`, answer: "Tea light" },
  { id: 787, clue: `C-FOOD`, answer: "Seafood" },
  { id: 788, clue: `B-COOL`, answer: "Be cool" },
  { id: 789, clue: `G-FORCE`, answer: "G-force" },
  { id: 790, clue: `T-BAG`, answer: "Tea bag" },
  { id: 791, clue: `P-NUT`, answer: "Peanut" },
  { id: 792, clue: `B-HAVE`, answer: "Behave" },
  { id: 793, clue: `X-PRESS`, answer: "Express" },
  { id: 794, clue: `O-RING`, answer: "O-ring" },
  { id: 795, clue: `C-SAW`, answer: "Seasaw" },
  { id: 796, clue: `B-HIND`, answer: "Behind" },
  { id: 797, clue: `T-POT`, answer: "Teapot" },
  { id: 798, clue: `G-UNIT`, answer: "G-unit" },
  { id: 799, clue: `A-LIST`, answer: "A-list" },
  { id: 800, clue: `C-SIDE`, answer: "Seaside" },
  { id: 801, clue: `MAN
BOARD`, answer: "Man Overboard" },
  { id: 802, clue: `STAND
—————
I`, answer: "I Understand" },
  { id: 803, clue: `THOUGHT`, answer: "Deep Thought" },
  { id: 804, clue: `R
E
A
D`, answer: "Read Up" },
  { id: 805, clue: `KNEE
LIGHTS`, answer: "Neon Lights" },
  { id: 806, clue: `ii ii`, answer: "See eye to eye" },
  { id: 807, clue: `TIMING TIMING`, answer: "Double Timing" },
  { id: 808, clue: `WAY
—————
S`, answer: "Subway" },
  { id: 809, clue: `LE
VEL`, answer: "Split Level" },
  { id: 810, clue: `DICE
DICE`, answer: "Paradise" },
  { id: 811, clue: `MCE MCE MCE`, answer: "Three Blind Mice" },
  { id: 812, clue: `LONG
WEAR`, answer: "Long Underwear" },
  { id: 813, clue: `HEAD
HEELS`, answer: "Head Over Heels" },
  { id: 814, clue: `CHART`, answer: "Off the Charts" },
  { id: 815, clue: `HISTORY HISTORY
HISTORY`, answer: "History repeats itself" },
  { id: 816, clue: `SYMPHON...`, answer: "Unfinished Symphony" },
  { id: 817, clue: `WOLF`, answer: "Wolf in sheep's clothing" },
  { id: 818, clue: `GIVE GIVE GIVE GIVE
GET GET GET GET`, answer: "Forgive and Forget" },
  { id: 819, clue: `ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE`, answer: "Tennis Shoes (Ten-issue)" },
  { id: 820, clue: `X Q Q Q ME`, answer: "Excuse Me" },
  { id: 821, clue: `HE'S/HIMSELF`, answer: "He's beside himself" },
  { id: 822, clue: `YOU ME`, answer: "Just between you and me" },
  { id: 823, clue: `TTTTTTTT`, answer: "Tea for two (T for 2)" },
  { id: 824, clue: `BUS`, answer: "Business" },
  { id: 825, clue: `PIPPED`, answer: "Pipped at the post" },
  { id: 826, clue: `EGG EGG`, answer: "Two eggs over easy" },
  { id: 827, clue: `PUNISHMENT`, answer: "Capital Punishment" },
  { id: 828, clue: `TOWN`, answer: "Man about town" },
  { id: 829, clue: `SEARCH
AND`, answer: "Search high and low" },
  { id: 830, clue: `FEET FEET FEET FEET
FEET FEET`, answer: "Six feet under" },
  { id: 831, clue: `NOON`, answer: "High Noon" },
  { id: 832, clue: `FALLING
LOVE`, answer: "Falling in love" },
  { id: 833, clue: `AGE`, answer: "Middle Age" },
  { id: 834, clue: `ROADS`, answer: "Crossroads" },
  { id: 835, clue: `MIND
MATTER`, answer: "Mind over matter" },
  { id: 836, clue: `KISS`, answer: "A big kiss" },
  { id: 837, clue: `TIME`, answer: "Time is up" },
  { id: 838, clue: `GROUND`, answer: "Six feet under ground" },
  { id: 839, clue: `CYCLE CYCLE CYCLE`, answer: "Tricycle" },
  { id: 840, clue: `DEAL`, answer: "Big Deal" },
  { id: 841, clue: `STOD`, answer: "Backwards" },
  { id: 842, clue: `POLICE`, answer: "Police on your tail" },
  { id: 843, clue: `LUCK`, answer: "Stroke of luck" },
  { id: 844, clue: `WEATHER`, answer: "Under the weather" },
  { id: 845, clue: `HEART`, answer: "Heart in the right place" },
  { id: 846, clue: `EYE`, answer: "Eye on the ball" },
  { id: 847, clue: `LIFE`, answer: "Life after death" },
  { id: 848, clue: `FRIENDS`, answer: "Friends in high places" },
  { id: 849, clue: `O_ER_T_O_`, answer: "Painless Operation" },
  { id: 850, clue: `TOUCH`, answer: "Touchdown" },
  { id: 851, clue: `VA DERS`, answer: "Space Invaders" },
  { id: 852, clue: `CHANCE`, answer: "Slim Chance" },
  { id: 853, clue: `BIRD`, answer: "Early Bird" },
  { id: 854, clue: `SECRET`, answer: "Top Secret" },
  { id: 855, clue: `PAINSTOP`, answer: "Stop and think" },
  { id: 856, clue: `JOB`, answer: "In between jobs" },
  { id: 857, clue: `GAGES`, answer: "Engages" },
  { id: 858, clue: `4GET`, answer: "Forget" },
  { id: 859, clue: `3D`, answer: "Third Dimension" },
  { id: 860, clue: `8 ATE 8`, answer: "Piece of cake" },
  { id: 861, clue: `B-SIDE`, answer: "Beside" },
  { id: 862, clue: `C-LEVEL`, answer: "Sea level" },
  { id: 863, clue: `G-STRING`, answer: "G-string" },
  { id: 864, clue: `T-BONE`, answer: "T-bone" },
  { id: 865, clue: `X-RAY`, answer: "X-ray" },
  { id: 866, clue: `P-POD`, answer: "Peas in a pod" },
  { id: 867, clue: `K-9`, answer: "Canine" },
  { id: 868, clue: `B-LINE`, answer: "Beeline" },
  { id: 869, clue: `Q-TIP`, answer: "Q-tip" },
  { id: 870, clue: `U-TURN`, answer: "U-turn" },
  { id: 871, clue: `I-OPENER`, answer: "Eye opener" },
  { id: 872, clue: `T-TIME`, answer: "Tea time" },
  { id: 873, clue: `E-MAIL`, answer: "Email" },
  { id: 874, clue: `B-BALL`, answer: "Basketball" },
  { id: 875, clue: `J-WALK`, answer: "Jaywalk" },
  { id: 876, clue: `C-SHORE`, answer: "Seashore" },
  { id: 877, clue: `U-BOAT`, answer: "U-boat" },
  { id: 878, clue: `V-NECK`, answer: "V-neck" },
  { id: 879, clue: `S-CAPE`, answer: "Escape" },
  { id: 880, clue: `B-STING`, answer: "Bee sting" },
  { id: 881, clue: `T-SHIRT`, answer: "T-shirt" },
  { id: 882, clue: `B-READY`, answer: "Be ready" },
  { id: 883, clue: `P-SOUP`, answer: "Pea soup" },
  { id: 884, clue: `I-LAND`, answer: "Island" },
  { id: 885, clue: `X-CHANGE`, answer: "Exchange" },
  { id: 886, clue: `T-LIGHT`, answer: "Tea light" },
  { id: 887, clue: `C-FOOD`, answer: "Seafood" },
  { id: 888, clue: `B-COOL`, answer: "Be cool" },
  { id: 889, clue: `G-FORCE`, answer: "G-force" },
  { id: 890, clue: `T-BAG`, answer: "Tea bag" },
  { id: 891, clue: `P-NUT`, answer: "Peanut" },
  { id: 892, clue: `B-HAVE`, answer: "Behave" },
  { id: 893, clue: `X-PRESS`, answer: "Express" },
  { id: 894, clue: `O-RING`, answer: "O-ring" },
  { id: 895, clue: `C-SAW`, answer: "Seasaw" },
  { id: 896, clue: `B-HIND`, answer: "Behind" },
  { id: 897, clue: `T-POT`, answer: "Teapot" },
  { id: 898, clue: `G-UNIT`, answer: "G-unit" },
  { id: 899, clue: `A-LIST`, answer: "A-list" },
  { id: 900, clue: `C-SIDE`, answer: "Seaside" },
  { id: 901, clue: `MAN
BOARD`, answer: "Man Overboard" },
  { id: 902, clue: `STAND
—————
I`, answer: "I Understand" },
  { id: 903, clue: `THOUGHT`, answer: "Deep Thought" },
  { id: 904, clue: `R
E
A
D`, answer: "Read Up" },
  { id: 905, clue: `KNEE
LIGHTS`, answer: "Neon Lights" },
  { id: 906, clue: `ii ii`, answer: "See eye to eye" },
  { id: 907, clue: `TIMING TIMING`, answer: "Double Timing" },
  { id: 908, clue: `WAY
—————
S`, answer: "Subway" },
  { id: 909, clue: `LE
VEL`, answer: "Split Level" },
  { id: 910, clue: `DICE
DICE`, answer: "Paradise" },
  { id: 911, clue: `MCE MCE MCE`, answer: "Three Blind Mice" },
  { id: 912, clue: `LONG
WEAR`, answer: "Long Underwear" },
  { id: 913, clue: `HEAD
HEELS`, answer: "Head Over Heels" },
  { id: 914, clue: `CHART`, answer: "Off the Charts" },
  { id: 915, clue: `HISTORY HISTORY
HISTORY`, answer: "History repeats itself" },
  { id: 916, clue: `SYMPHON...`, answer: "Unfinished Symphony" },
  { id: 917, clue: `WOLF`, answer: "Wolf in sheep's clothing" },
  { id: 918, clue: `GIVE GIVE GIVE GIVE
GET GET GET GET`, answer: "Forgive and Forget" },
  { id: 919, clue: `ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE ISSUE ISSUE
ISSUE`, answer: "Tennis Shoes (Ten-issue)" },
  { id: 920, clue: `X Q Q Q ME`, answer: "Excuse Me" },
  { id: 921, clue: `HE'S/HIMSELF`, answer: "He's beside himself" },
  { id: 922, clue: `YOU ME`, answer: "Just between you and me" },
  { id: 923, clue: `TTTTTTTT`, answer: "Tea for two (T for 2)" },
  { id: 924, clue: `BUS`, answer: "Business" },
  { id: 925, clue: `PIPPED`, answer: "Pipped at the post" },
  { id: 926, clue: `EGG EGG`, answer: "Two eggs over easy" },
  { id: 927, clue: `PUNISHMENT`, answer: "Capital Punishment" },
  { id: 928, clue: `TOWN`, answer: "Man about town" },
  { id: 929, clue: `SEARCH
AND`, answer: "Search high and low" },
  { id: 930, clue: `FEET FEET FEET FEET
FEET FEET`, answer: "Six feet under" },
  { id: 931, clue: `NOON`, answer: "High Noon" },
  { id: 932, clue: `FALLING
LOVE`, answer: "Falling in love" },
  { id: 933, clue: `AGE`, answer: "Middle Age" },
  { id: 934, clue: `ROADS`, answer: "Crossroads" },
  { id: 935, clue: `MIND
MATTER`, answer: "Mind over matter" },
  { id: 936, clue: `KISS`, answer: "A big kiss" },
  { id: 937, clue: `TIME`, answer: "Time is up" },
  { id: 938, clue: `GROUND`, answer: "Six feet under ground" },
  { id: 939, clue: `CYCLE CYCLE CYCLE`, answer: "Tricycle" },
  { id: 940, clue: `DEAL`, answer: "Big Deal" },
  { id: 941, clue: `STOD`, answer: "Backwards" },
  { id: 942, clue: `POLICE`, answer: "Police on your tail" },
  { id: 943, clue: `LUCK`, answer: "Stroke of luck" },
  { id: 944, clue: `WEATHER`, answer: "Under the weather" },
  { id: 945, clue: `HEART`, answer: "Heart in the right place" },
  { id: 946, clue: `EYE`, answer: "Eye on the ball" },
  { id: 947, clue: `LIFE`, answer: "Life after death" },
  { id: 948, clue: `FRIENDS`, answer: "Friends in high places" },
  { id: 949, clue: `O_ER_T_O_`, answer: "Painless Operation" },
  { id: 950, clue: `TOUCH`, answer: "Touchdown" },
  { id: 951, clue: `VA DERS`, answer: "Space Invaders" },
  { id: 952, clue: `CHANCE`, answer: "Slim Chance" },
  { id: 953, clue: `BIRD`, answer: "Early Bird" },
  { id: 954, clue: `SECRET`, answer: "Top Secret" },
  { id: 955, clue: `PAINSTOP`, answer: "Stop and think" },
  { id: 956, clue: `JOB`, answer: "In between jobs" },
  { id: 957, clue: `GAGES`, answer: "Engages" },
  { id: 958, clue: `4GET`, answer: "Forget" },
  { id: 959, clue: `3D`, answer: "Third Dimension" },
  { id: 960, clue: `8 ATE 8`, answer: "Piece of cake" },
  { id: 961, clue: `B-SIDE`, answer: "Beside" },
  { id: 962, clue: `C-LEVEL`, answer: "Sea level" },
  { id: 963, clue: `G-STRING`, answer: "G-string" },
  { id: 964, clue: `T-BONE`, answer: "T-bone" },
  { id: 965, clue: `X-RAY`, answer: "X-ray" },
  { id: 966, clue: `P-POD`, answer: "Peas in a pod" },
  { id: 967, clue: `K-9`, answer: "Canine" },
  { id: 968, clue: `B-LINE`, answer: "Beeline" },
  { id: 969, clue: `Q-TIP`, answer: "Q-tip" },
  { id: 970, clue: `U-TURN`, answer: "U-turn" },
  { id: 971, clue: `I-OPENER`, answer: "Eye opener" },
  { id: 972, clue: `T-TIME`, answer: "Tea time" },
  { id: 973, clue: `E-MAIL`, answer: "Email" },
  { id: 974, clue: `B-BALL`, answer: "Basketball" },
  { id: 975, clue: `J-WALK`, answer: "Jaywalk" },
  { id: 976, clue: `C-SHORE`, answer: "Seashore" },
  { id: 977, clue: `U-BOAT`, answer: "U-boat" },
  { id: 978, clue: `V-NECK`, answer: "V-neck" },
  { id: 979, clue: `S-CAPE`, answer: "Escape" },
  { id: 980, clue: `B-STING`, answer: "Bee sting" },
  { id: 981, clue: `T-SHIRT`, answer: "T-shirt" },
  { id: 982, clue: `B-READY`, answer: "Be ready" },
  { id: 983, clue: `P-SOUP`, answer: "Pea soup" },
  { id: 984, clue: `I-LAND`, answer: "Island" },
  { id: 985, clue: `X-CHANGE`, answer: "Exchange" },
  { id: 986, clue: `T-LIGHT`, answer: "Tea light" },
  { id: 987, clue: `C-FOOD`, answer: "Seafood" },
  { id: 988, clue: `B-COOL`, answer: "Be cool" },
  { id: 989, clue: `G-FORCE`, answer: "G-force" },
  { id: 990, clue: `T-BAG`, answer: "Tea bag" },
  { id: 991, clue: `P-NUT`, answer: "Peanut" },
  { id: 992, clue: `B-HAVE`, answer: "Behave" },
  { id: 993, clue: `X-PRESS`, answer: "Express" },
  { id: 994, clue: `O-RING`, answer: "O-ring" },
  { id: 995, clue: `C-SAW`, answer: "Seasaw" },
  { id: 996, clue: `B-HIND`, answer: "Behind" },
  { id: 997, clue: `T-POT`, answer: "Teapot" },
  { id: 998, clue: `G-UNIT`, answer: "G-unit" },
  { id: 999, clue: `A-LIST`, answer: "A-list" },
  { id: 1000, clue: `C-SIDE`, answer: "Seaside" },
];